<?php

use App\Http\Controllers\StupidLog\LibraryController;
use App\Http\Controllers\StupidLog\GameDetailsController;
use App\Http\Controllers\StupidLog\OwnedDlcController;
use App\Http\Controllers\StupidLog\OwnershipCopyController;
use App\Http\Controllers\StupidLog\ProviderController;
use App\Http\Controllers\StupidLog\SnapshotController;
use App\Http\Controllers\StupidLog\SetupController;
use App\Http\Controllers\StupidLog\SettingsController;
use App\Http\Controllers\StupidLog\StatsController;
use App\Http\Controllers\StupidLog\StupidLogController;
use Illuminate\Support\Facades\Route;

Route::get('/setup', [SetupController::class, 'setup'])->name('setup');
Route::post('/setup', [SetupController::class, 'storeSetup'])->name('setup.store');

Route::get('/', [StupidLogController::class, 'home'])->name('home');
Route::get('/library', [LibraryController::class, 'library'])->name('library');
Route::get('/library-games', [LibraryController::class, 'libraryGames'])->name('library-games.index');
Route::post('/library-games', [StupidLogController::class, 'storeLibraryGame'])->name('library-games.store');
Route::post('/library-games/cover', [StupidLogController::class, 'uploadGameCover'])->name('library-games.cover.store');
Route::get('/library-games/manual-duplicates', [StupidLogController::class, 'manualDuplicates'])->name('library-games.manual-duplicates');
Route::get('/provider-search', [ProviderController::class, 'providerSearch'])->name('provider-search');
Route::post('/provider-import-drafts', [ProviderController::class, 'storeProviderImportDraft'])->name('provider-import-drafts.store');
Route::delete('/provider-import-drafts/{providerImportDraft}', [ProviderController::class, 'cancelProviderImportDraft'])->name('provider-import-drafts.destroy');
Route::get('/games/{libraryGame}', [GameDetailsController::class, 'gameDetails'])->name('games.show');
Route::patch('/games/{libraryGame}', [StupidLogController::class, 'updateLibraryGame'])->name('games.update');
Route::delete('/games/{libraryGame}', [StupidLogController::class, 'destroyLibraryGame'])->name('games.destroy');
Route::patch('/games/{libraryGame}/platform-devices', [StupidLogController::class, 'updatePlatformDevices'])->name('games.platform-devices.update');
Route::post('/games/{libraryGame}/ownership-copies', [OwnershipCopyController::class, 'storeOwnershipCopy'])->name('games.ownership-copies.store');
Route::patch('/ownership-copies/{ownershipCopy}', [OwnershipCopyController::class, 'updateOwnershipCopy'])->name('ownership-copies.update');
Route::delete('/ownership-copies/{ownershipCopy}', [OwnershipCopyController::class, 'destroyOwnershipCopy'])->name('ownership-copies.destroy');
Route::post('/games/{libraryGame}/dlcs/refresh', [StupidLogController::class, 'refreshDlcs'])->name('games.dlcs.refresh');
Route::post('/games/{libraryGame}/owned-dlcs', [OwnedDlcController::class, 'storeOwnedDlc'])->name('games.owned-dlcs.store');
Route::patch('/owned-dlcs/{ownedDlc}', [OwnedDlcController::class, 'updateOwnedDlc'])->name('owned-dlcs.update');
Route::delete('/owned-dlcs/{ownedDlc}', [OwnedDlcController::class, 'destroyOwnedDlc'])->name('owned-dlcs.destroy');
Route::get('/stats', [StatsController::class, 'stats'])->name('stats');
Route::get('/snapshots', [SnapshotController::class, 'snapshots'])->name('snapshots');
Route::get('/snapshots-feed', [SnapshotController::class, 'snapshotFeed'])->name('snapshots.feed');
Route::post('/snapshots', [SnapshotController::class, 'createSnapshot'])->name('snapshots.store');
Route::get('/snapshots/{snapshotRun}', [SnapshotController::class, 'snapshotDetails'])->name('snapshots.show');
Route::get('/snapshots/{snapshotRun}/games', [SnapshotController::class, 'snapshotGames'])->name('snapshots.games');
Route::get('/snapshots/{snapshotRun}/eligible-best-games', [SnapshotController::class, 'snapshotEligibleBestGames'])->name('snapshots.eligible-best-games');
Route::patch('/snapshots/{snapshotRun}/resnap', [SnapshotController::class, 'resnapSnapshot'])->name('snapshots.resnap');
Route::patch('/snapshots/{snapshotRun}/confirm', [SnapshotController::class, 'confirmSnapshot'])->name('snapshots.confirm');
Route::patch('/snapshots/{snapshotRun}/best-games', [SnapshotController::class, 'updateSnapshotBestGames'])->name('snapshots.best-games.update');
Route::delete('/snapshots/{snapshotRun}', [SnapshotController::class, 'destroySnapshot'])->name('snapshots.destroy');
Route::get('/settings', [SettingsController::class, 'settings'])->name('settings');
Route::patch('/settings', [SettingsController::class, 'updateSettings'])->name('settings.update');
Route::post('/settings/reset', [SettingsController::class, 'resetApp'])->name('settings.reset');
Route::post('/settings/igdb/test', [SettingsController::class, 'testIgdbCredentials'])->name('settings.igdb.test');
Route::post('/settings/steam/test', [SettingsController::class, 'testSteamCredentials'])->name('settings.steam.test');
