import { BarChart3, ChevronLeft, ChevronRight, Clock3, DollarSign, Gamepad2, Trophy } from 'lucide-react';
import { useMemo, useState } from 'react';
import AppLayout from '../Components/AppLayout';
import { ConfirmedYearStats, GrowthMetric, PlatformBreakdown, StatsArchiveGame, StatsData, StatusBreakdown } from '../types';

type TabKey = 'overview' | 'breakdowns' | 'progression' | 'archive';
type StatView = StatsData & { year?: number; growth?: Record<string, GrowthMetric>; best_games?: ConfirmedYearStats['best_games'] };
type Slice = { label: string; value: number; color: string; growth?: GrowthMetric | null };

const tabs: Array<{ key: TabKey; title: string; sub: string }> = [
    { key: 'overview', title: 'Overview', sub: 'core totals' },
    { key: 'breakdowns', title: 'Breakdowns', sub: 'charts' },
    { key: 'progression', title: 'Progression', sub: 'completion' },
    { key: 'archive', title: 'Game Archive', sub: 'records' },
];
const palette = ['#9BE44D', '#101516', '#8FA29A', '#C7D2CC', '#7AB66C', '#D8E4D8', '#6D7D76', '#B7FF63'];

function n(value: unknown) { const x = Number(value ?? 0); return Number.isFinite(x) ? x : 0; }
function num(value: unknown, d = 0) { return n(value).toLocaleString(undefined, { maximumFractionDigits: d, minimumFractionDigits: d }); }
function money(value: unknown) { const x = n(value); return Math.abs(x) >= 1000 ? `$${(x / 1000).toLocaleString(undefined, { maximumFractionDigits: 1 })}K` : `$${num(x, x % 1 ? 2 : 0)}`; }
function hours(value: unknown) { return `${num(value, n(value) % 1 ? 1 : 0)}H`; }
function growth(current: number, previous: number): GrowthMetric { const delta = Number((current - previous).toFixed(1)); return { delta, percentage: previous > 0 ? Number(((delta / previous) * 100).toFixed(1)) : null }; }
function metricGrowth(key: keyof StatsData, current: StatView, previous?: StatView | null) { return current.growth?.[String(key)] ?? (previous ? growth(n(current[key]), n(previous[key])) : null); }
function slices<T extends { label: string }>(items: T[], getter: (item: T) => number, previousItems: T[] = []): Slice[] {
    return items.map((item, i) => { const previous = previousItems.find((p) => p.label === item.label); const value = getter(item); return { label: item.label, value, color: palette[i % palette.length], growth: previous ? growth(value, getter(previous)) : null }; }).filter((s) => s.value > 0);
}

function DeltaBadge({ value, compact = false }: { value?: GrowthMetric | null; compact?: boolean }) {
    if (!value) return <span className={`${compact ? 'px-2 py-0.5 text-[10px]' : 'px-3 py-1 text-xs'} inline-flex rounded-full border border-black/10 bg-white/55 font-black text-black/35`}>— | no baseline</span>;
    const pos = value.delta > 0; const neg = value.delta < 0; const arrow = pos ? '▲' : neg ? '▼' : '→'; const percent = value.percentage === null ? 'new' : `${value.percentage > 0 ? '+' : ''}${num(value.percentage, 1)}%`;
    return <span className={`${compact ? 'px-2 py-0.5 text-[10px]' : 'px-3 py-1 text-xs'} inline-flex rounded-full font-black ring-1 ring-black/5 ${pos ? 'bg-[#b7ff63] text-black' : neg ? 'bg-[#ffe0dd] text-[#ad2c21]' : 'bg-[#edf1ec] text-black/50'}`}>{pos ? '+' : ''}{num(value.delta, Math.abs(value.delta) % 1 ? 1 : 0)} | {percent} {arrow}</span>;
}
function ProgressBar({ value, large = false }: { value: number; large?: boolean }) { return <div className={`${large ? 'h-4' : 'h-2.5'} overflow-hidden rounded-full bg-black/8`}><div className="h-full rounded-full bg-[#9BE44D]" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
function Switch<T extends string>({ value, options, onChange }: { value: T; options: Array<{ value: T; label: string }>; onChange: (value: T) => void }) { return <div className="inline-flex rounded-full bg-black/7 p-1">{options.map((o) => <button key={o.value} type="button" onClick={() => onChange(o.value)} className={`rounded-full px-4 py-2 text-xs font-black uppercase tracking-[0.12em] transition ${value === o.value ? 'bg-black text-[#b7ff63] shadow-sm' : 'text-black/42 hover:text-black'}`}>{o.label}</button>)}</div>; }

function StatCard({ label, value, detail, delta, icon: Icon }: { label: string; value: string; detail: string; delta?: GrowthMetric | null; icon: typeof Gamepad2 }) {
    return <article className="rounded-[28px] border border-black/10 bg-white/80 p-5 shadow-[0_20px_55px_rgb(9_14_12/0.07)] backdrop-blur"><div className="flex items-center justify-between gap-4"><div className="text-[11px] font-black uppercase tracking-[0.2em] text-black/40">{label}</div><div className="grid size-10 place-items-center rounded-2xl bg-black text-[#b7ff63]"><Icon size={20} strokeWidth={3} /></div></div><div className="mt-5 text-3xl font-black text-black">{value}</div><div className="mt-2 text-sm font-bold text-black/42">{detail}</div><div className="mt-4"><DeltaBadge value={delta} /></div></article>;
}

function Chart({ title, note, total, center, data, delta, format = (x: number) => num(x, x % 1 ? 1 : 0) }: { title: string; note: string; total: string; center: string; data: Slice[]; delta?: GrowthMetric | null; format?: (value: number) => string }) {
    const r = 66; const c = 2 * Math.PI * r; const sum = data.reduce((a, b) => a + b.value, 0); let off = 0;
    return <article className="min-h-[420px] rounded-[30px] border border-black/10 bg-white/78 p-5 shadow-[0_22px_65px_rgb(9_14_12/0.08)] backdrop-blur"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-black text-black">{title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-[0.14em] text-black/38">{note}</p></div><DeltaBadge value={delta} compact /></div><div className="mt-6 grid gap-5 lg:grid-cols-[230px_1fr]"><div className="grid place-items-center rounded-[26px] bg-[#f4f7f2] p-4 ring-1 ring-black/6"><div className="relative size-[220px]"><svg viewBox="0 0 220 220" className="size-full"><circle cx="110" cy="110" r={r} fill="none" stroke="rgba(16,21,22,0.08)" strokeWidth="20" />{sum > 0 && data.map((s) => { const len = (s.value / sum) * c; const seg = <circle key={s.label} cx="110" cy="110" r={r} fill="none" stroke={s.color} strokeWidth="20" strokeDasharray={`${len} ${c - len}`} strokeDashoffset={-off} strokeLinecap="round" transform="rotate(-90 110 110)" />; off += len; return seg; })}</svg><div className="absolute inset-0 grid place-items-center text-center"><div><div className="text-3xl font-black text-black">{total}</div><div className="mt-1 text-[10px] font-black uppercase tracking-[0.16em] text-black/38">{center}</div></div></div></div></div><div className="max-h-[295px] overflow-y-auto pr-1"><div className="grid gap-3">{data.length === 0 && <div className="rounded-[22px] border border-dashed border-black/14 bg-black/[0.02] p-5 text-sm font-bold text-black/42">No chart data yet.</div>}{data.map((s) => { const p = sum > 0 ? (s.value / sum) * 100 : 0; return <div key={s.label} className="rounded-[22px] bg-[#f7faf5] p-3 ring-1 ring-black/6"><div className="flex items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-2 text-sm font-black text-black/75"><span className="size-3 rounded-full" style={{ backgroundColor: s.color }} /><span className="truncate">{s.label}</span></span><span className="text-sm font-black text-black">{num(p, 1)}%</span></div><div className="mt-2 flex items-center justify-between gap-3 text-xs font-black text-black/38"><span>{format(s.value)}</span><DeltaBadge value={s.growth} compact /></div></div>; })}</div></div></div></article>;
}

function Overview({ stats, previous, selectedYear }: { stats: StatView; previous?: StatView | null; selectedYear?: ConfirmedYearStats | null }) {
    return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Games" value={num(stats.library_games)} detail="Library game entries" delta={metricGrowth('library_games', stats, previous)} icon={Gamepad2} /><StatCard label="Completed Games" value={num(stats.completed)} detail="Completed + 100%" delta={metricGrowth('completed', stats, previous)} icon={Trophy} /><StatCard label="100% Games" value={num(stats.hundred_percent)} detail="Perfect achievement runs" delta={metricGrowth('hundred_percent', stats, previous)} icon={Trophy} /><StatCard label="Playtime" value={hours(stats.playtime_hours)} detail="Total tracked hours" delta={metricGrowth('playtime_hours', stats, previous)} icon={Clock3} /></div><div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr_0.8fr]"><article className="rounded-[28px] border border-black/10 bg-black p-5 text-white shadow-[0_20px_55px_rgb(9_14_12/0.14)]"><div className="flex items-center justify-between gap-4"><div className="text-[11px] font-black uppercase tracking-[0.2em] text-[#b7ff63]/70">Achievements</div><div className="grid size-10 place-items-center rounded-2xl bg-[#b7ff63] text-black"><Trophy size={20} strokeWidth={3} /></div></div><div className="mt-5 flex items-end justify-between gap-4"><div><div className="text-3xl font-black">{num(stats.earned_achievements)} / {num(stats.total_achievements)}</div><div className="mt-2 text-sm font-bold text-white/42">{num(stats.achievement_progress, 1)}% progression</div></div><DeltaBadge value={metricGrowth('achievement_progress', stats, previous)} /></div><div className="mt-5 h-4 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#b7ff63]" style={{ width: `${Math.max(0, Math.min(100, stats.achievement_progress))}%` }} /></div></article><StatCard label="Base Value" value={money(stats.base_value)} detail="Digital/Physical + owned DLCs" delta={metricGrowth('base_value', stats, previous)} icon={DollarSign} /><StatCard label="Paid Value" value={money(stats.purchased_value)} detail="What you paid" delta={metricGrowth('purchased_value', stats, previous)} icon={DollarSign} /></div>{selectedYear && <BestOfYear year={selectedYear} />}</div>;
}

function BestOfYear({ year }: { year: ConfirmedYearStats }) {
    return <article className="rounded-[30px] border border-black/10 bg-[#eff4ec] p-6 shadow-[0_22px_65px_rgb(9_14_12/0.07)]"><div className="flex items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[0.22em] text-black/38">Best of the year</div><h3 className="mt-2 text-3xl font-black">{year.year} favorites</h3></div><div className="text-sm font-black text-black/38">{year.best_games.length}/5 selected</div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{year.best_games.length === 0 && <div className="rounded-[24px] border border-dashed border-black/15 bg-white/70 p-6 text-sm font-bold text-black/42 md:col-span-2 xl:col-span-5">No favorite games were selected for this confirmed year.</div>}{year.best_games.map((game) => <div key={`${game.library_game_id}-${game.rank}`} className="overflow-hidden rounded-[24px] bg-black text-white"><div className="aspect-[4/3] bg-white/8">{game.cover_url ? <img src={game.cover_url} alt="" className="size-full object-cover" /> : <div className="grid size-full place-items-center text-3xl font-black text-[#b7ff63]">#{game.rank}</div>}</div><div className="p-4"><div className="text-xs font-black uppercase tracking-[0.16em] text-[#b7ff63]">#{game.rank}</div><div className="mt-2 truncate text-base font-black">{game.title}</div><div className="mt-1 truncate text-xs font-bold text-white/45">{game.platform} · {game.status}</div></div></div>)}</div></article>;
}

function Breakdowns({ stats, previous }: { stats: StatView; previous?: StatView | null }) {
    const [gamesMode, setGamesMode] = useState<'platform' | 'status'>('platform');
    const [achievementMode, setAchievementMode] = useState<'earned' | 'total'>('earned');
    const [valueMode, setValueMode] = useState<'base' | 'paid'>('base');
    const [includeDlcs, setIncludeDlcs] = useState(true);
    const platforms = stats.breakdowns.platforms; const prevPlatforms = previous?.breakdowns.platforms ?? []; const statuses = stats.breakdowns.statuses; const prevStatuses = previous?.breakdowns.statuses ?? [];
    const gameSlices = gamesMode === 'platform' ? slices<PlatformBreakdown>(platforms, (x) => x.library_games, prevPlatforms) : slices<StatusBreakdown>(statuses, (x) => x.library_games, prevStatuses);
    const achievementKey = achievementMode === 'total' ? 'total_achievements' : 'earned_achievements';
    const achievementSlices = slices<PlatformBreakdown>(platforms, (x) => n(x[achievementKey]), prevPlatforms);
    const valueGetter = (x: PlatformBreakdown) => valueMode === 'base' ? (includeDlcs ? x.base_value : n(x.base_value_without_dlcs ?? x.base_value)) : (includeDlcs ? x.purchased_value : n(x.purchased_value_without_dlcs ?? x.purchased_value));
    const valueSlices = slices<PlatformBreakdown>(platforms, valueGetter, prevPlatforms); const totalValue = valueSlices.reduce((a, b) => a + b.value, 0); const prevValue = prevPlatforms.reduce((a, b) => a + valueGetter(b), 0);
    return <div className="grid gap-5 xl:grid-cols-2"><article className="rounded-[30px] border border-black/10 bg-[#eef4eb] p-5 shadow-[0_22px_65px_rgb(9_14_12/0.06)] xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[0.22em] text-black/38">Rounded charts</div><h2 className="mt-1 text-3xl font-black">Breakdown cockpit</h2></div><p className="max-w-xl text-sm font-bold leading-relaxed text-black/45">Values count only Digital and Physical ownership copies. DLC value counts only separately Owned DLCs.</p></div></article><div className="space-y-3"><Switch value={gamesMode} options={[{ value: 'platform', label: 'By Platform' }, { value: 'status', label: 'By Status' }]} onChange={setGamesMode} /><Chart title="Total Games" note={gamesMode === 'platform' ? 'Grouped by platform' : 'Grouped by status'} total={num(stats.library_games)} center="games" data={gameSlices} delta={metricGrowth('library_games', stats, previous)} /></div><Chart title="Playtime" note="Only by platform" total={hours(stats.playtime_hours)} center="hours" data={slices<PlatformBreakdown>(platforms, (x) => x.playtime_hours, prevPlatforms)} delta={metricGrowth('playtime_hours', stats, previous)} format={hours} /><div className="space-y-3"><Switch value={achievementMode} options={[{ value: 'earned', label: 'Earned' }, { value: 'total', label: 'Total' }]} onChange={setAchievementMode} /><Chart title="Achievements" note={`Only by platform · ${achievementMode}`} total={num(achievementMode === 'total' ? stats.total_achievements : stats.earned_achievements)} center={achievementMode} data={achievementSlices} delta={metricGrowth(achievementMode === 'total' ? 'total_achievements' : 'earned_achievements', stats, previous)} /></div><div className="space-y-3"><div className="flex flex-wrap items-center gap-2"><Switch value={valueMode} options={[{ value: 'base', label: 'Base' }, { value: 'paid', label: 'Paid' }]} onChange={setValueMode} /><button type="button" onClick={() => setIncludeDlcs((v) => !v)} className={`rounded-full px-4 py-2 text-xs font-black uppercase tracking-[0.12em] ring-1 ring-black/10 transition ${includeDlcs ? 'bg-[#b7ff63] text-black' : 'bg-white/70 text-black/45 hover:text-black'}`}>{includeDlcs ? 'DLCs included' : 'DLCs excluded'}</button></div><Chart title="Library Value" note={`Only by platform · ${valueMode} value`} total={money(totalValue)} center={includeDlcs ? 'with DLCs' : 'no DLCs'} data={valueSlices} delta={previous ? growth(totalValue, prevValue) : null} format={money} /></div></div>;
}

function Progression({ stats, previous }: { stats: StatView; previous?: StatView | null }) {
    const platforms = [...stats.breakdowns.platforms].sort((a, b) => b.library_games - a.library_games); const prevPlatforms = previous?.breakdowns.platforms ?? [];
    return <div className="grid gap-5 xl:grid-cols-2"><article className="rounded-[30px] border border-black/10 bg-black p-6 text-white shadow-[0_22px_65px_rgb(9_14_12/0.14)] xl:col-span-2"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[0.22em] text-[#b7ff63]/70">Progression</div><h2 className="mt-2 text-3xl font-black">Platform progress map</h2></div><div className="text-right"><div className="text-3xl font-black">{num(stats.achievement_progress, 1)}%</div><div className="mt-1 text-sm font-bold text-white/42">global achievement progression</div></div></div><div className="mt-5 h-4 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#b7ff63]" style={{ width: `${Math.max(0, Math.min(100, stats.achievement_progress))}%` }} /></div></article><section className="rounded-[30px] border border-black/10 bg-[#eef4eb] p-5 shadow-[0_22px_65px_rgb(9_14_12/0.06)]"><div className="mb-4"><div className="text-xs font-black uppercase tracking-[0.22em] text-black/38">Achievements</div><h3 className="mt-1 text-2xl font-black">Earned / Total by platform</h3></div><div className="max-h-[570px] overflow-y-auto pr-1"><div className="grid gap-3">{platforms.filter((p) => p.total_achievements > 0).map((p) => { const prev = prevPlatforms.find((x) => x.label === p.label); return <div key={p.label} className="rounded-[26px] bg-white/78 p-5 ring-1 ring-black/8"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xl font-black text-black">{p.label}</div><div className="mt-1 text-sm font-bold text-black/42">{num(p.earned_achievements)} / {num(p.total_achievements)} achievements</div></div><div className="text-right"><div className="text-2xl font-black text-black">{num(p.achievement_progress, 1)}%</div><div className="mt-1"><DeltaBadge value={prev ? growth(p.achievement_progress, prev.achievement_progress) : null} compact /></div></div></div><div className="mt-4"><ProgressBar value={p.achievement_progress} large /></div></div>; })}{platforms.every((p) => p.total_achievements <= 0) && <Empty text="No achievement totals are available yet." />}</div></div></section><section className="rounded-[30px] border border-black/10 bg-[#eef4eb] p-5 shadow-[0_22px_65px_rgb(9_14_12/0.06)]"><div className="mb-4"><div className="text-xs font-black uppercase tracking-[0.22em] text-black/38">Status</div><h3 className="mt-1 text-2xl font-black">Status split by platform</h3></div><div className="max-h-[570px] overflow-y-auto pr-1"><div className="grid gap-3">{platforms.map((p) => <StatusStack key={p.label} platform={p} previous={prevPlatforms.find((x) => x.label === p.label)} />)}{platforms.length === 0 && <Empty text="Add games to build status progression." />}</div></div></section></div>;
}

function StatusStack({ platform, previous }: { platform: PlatformBreakdown; previous?: PlatformBreakdown }) {
    const statuses = platform.statuses ?? []; const total = Math.max(1, platform.library_games);
    return <div className="rounded-[26px] bg-white/78 p-5 ring-1 ring-black/8"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xl font-black text-black">{platform.label}</div><div className="mt-1 text-sm font-bold text-black/42">{num(platform.library_games)} games divided by status</div></div><DeltaBadge value={previous ? growth(platform.library_games, previous.library_games) : null} compact /></div><div className="mt-4 flex h-6 overflow-hidden rounded-full bg-black/8">{statuses.length === 0 && <div className="h-full w-full bg-black/10" />}{statuses.map((s, i) => <div key={s.label} className="h-full" style={{ width: `${(s.library_games / total) * 100}%`, backgroundColor: palette[i % palette.length] }} />)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{statuses.map((s, i) => <div key={s.label} className="flex items-center justify-between gap-2 rounded-2xl bg-[#f6faf4] px-3 py-2 text-xs font-black text-black/60"><span className="flex min-w-0 items-center gap-2"><span className="size-2.5 rounded-full" style={{ backgroundColor: palette[i % palette.length] }} /><span className="truncate">{s.label}</span></span><span>{num(s.library_games)} · {num((s.library_games / total) * 100, 1)}%</span></div>)}</div></div>;
}

function Archive({ stats, previous, selectedYear }: { stats: StatView; previous?: StatView | null; selectedYear?: ConfirmedYearStats | null }) {
    return <div className="space-y-5"><article className="rounded-[30px] border border-black/10 bg-black p-6 text-white shadow-[0_22px_65px_rgb(9_14_12/0.14)]"><div className="text-xs font-black uppercase tracking-[0.22em] text-[#b7ff63]/70">Game Archive</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl font-black">Records only, no filler cards</h2><p className="max-w-lg text-sm font-bold text-white/45">{selectedYear ? `Frozen from the ${selectedYear.year} confirmed snapshot` : 'Live all-time library records'}</p></div></article><div className="grid gap-5 xl:grid-cols-3"><ArchiveList title="Most Played" sub="Playtime record" games={stats.archive?.most_played ?? []} metric="playtime" delta={metricGrowth('playtime_hours', stats, previous)} /><ArchiveList title="Biggest Base Price" sub="Base value record" games={stats.archive?.biggest_base_price ?? []} metric="base" delta={metricGrowth('base_value', stats, previous)} /><ArchiveList title="Biggest Paid Price" sub="Paid value record" games={stats.archive?.biggest_paid_price ?? []} metric="paid" delta={metricGrowth('purchased_value', stats, previous)} /></div></div>;
}
function ArchiveList({ title, sub, games, metric, delta }: { title: string; sub: string; games: StatsArchiveGame[]; metric: 'playtime' | 'base' | 'paid'; delta?: GrowthMetric | null }) { const value = (g: StatsArchiveGame) => metric === 'playtime' ? hours(g.playtime_hours) : metric === 'base' ? money(g.base_value) : money(g.purchased_value); return <section className="rounded-[30px] border border-black/10 bg-white/80 p-5 shadow-[0_22px_65px_rgb(9_14_12/0.07)]"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[0.22em] text-black/38">{sub}</div><h3 className="mt-1 text-2xl font-black">{title}</h3></div><DeltaBadge value={delta} compact /></div><div className="mt-4 grid gap-3">{games.length === 0 && <Empty text="No games match this archive record yet." />}{games.map((g, i) => <div key={`${g.library_game_id}-${title}`} className="grid grid-cols-[54px_1fr_auto] items-center gap-3 rounded-[24px] bg-[#f6faf4] p-3 ring-1 ring-black/6"><div className="aspect-square overflow-hidden rounded-2xl bg-black/8">{g.cover_url ? <img src={g.cover_url} alt="" className="size-full object-cover" /> : <div className="grid size-full place-items-center text-sm font-black text-black/35">#{i + 1}</div>}</div><div className="min-w-0"><div className="truncate text-base font-black text-black">{g.title}</div><div className="mt-1 truncate text-xs font-bold text-black/42">{g.platform} · {g.status}</div></div><div className="text-right"><div className="text-lg font-black text-black">{value(g)}</div><div className="text-[10px] font-black uppercase tracking-[0.12em] text-black/35">#{i + 1}</div></div></div>)}</div></section>; }
function Empty({ text }: { text: string }) { return <div className="rounded-[24px] border border-dashed border-black/14 bg-white/70 p-6 text-sm font-bold text-black/42">{text}</div>; }

function SlideNav({ active, setActive }: { active: TabKey; setActive: (tab: TabKey) => void }) {
    const index = tabs.findIndex((tab) => tab.key === active); const go = (step: number) => setActive(tabs[(index + step + tabs.length) % tabs.length].key);
    return <div className="sticky bottom-5 z-30 mt-7 flex justify-center px-2"><div className="flex max-w-full items-center gap-2 overflow-x-auto rounded-[26px] border border-black/10 bg-black p-2 shadow-[0_22px_70px_rgb(0_0_0/0.24)]"><button type="button" onClick={() => go(-1)} className="grid size-11 shrink-0 place-items-center rounded-[20px] bg-white/8 text-white/70 hover:text-[#b7ff63]"><ChevronLeft size={18} /></button>{tabs.map((tab) => <button key={tab.key} type="button" onClick={() => setActive(tab.key)} className={`min-w-[155px] rounded-[20px] px-5 py-3 text-left transition ${active === tab.key ? 'bg-[#b7ff63] text-black' : 'bg-white/7 text-white/45 hover:text-white'}`}><div className="text-sm font-black">{tab.title}</div><div className="text-[10px] font-black uppercase tracking-[0.16em] opacity-50">{tab.sub}</div></button>)}<button type="button" onClick={() => go(1)} className="grid size-11 shrink-0 place-items-center rounded-[20px] bg-white/8 text-white/70 hover:text-[#b7ff63]"><ChevronRight size={18} /></button></div></div>;
}

export default function Stats({ stats, confirmedYears = [] }: { stats: StatsData; confirmedYears?: ConfirmedYearStats[] }) {
    const [view, setView] = useState<'all-time' | string>('all-time'); const [active, setActive] = useState<TabKey>('overview');
    const yearsAsc = useMemo(() => [...confirmedYears].sort((a, b) => a.year - b.year), [confirmedYears]); const yearsDesc = useMemo(() => [...confirmedYears].sort((a, b) => b.year - a.year), [confirmedYears]);
    const selectedYear = view === 'all-time' ? null : confirmedYears.find((y) => String(y.year) === view) ?? null; const earlier = selectedYear ? yearsAsc.filter((y) => y.year < selectedYear.year) : []; const previousYear = earlier.length > 0 ? earlier[earlier.length - 1] : null; const latestYear = yearsDesc[0] ?? null;
    const current: StatView = selectedYear ?? stats; const previous: StatView | null = selectedYear ? previousYear : latestYear; const displayedYear = selectedYear?.year ?? latestYear?.year ?? null; const yearIndex = displayedYear ? yearsAsc.findIndex((y) => y.year === displayedYear) : -1;
    const stepYear = (dir: number) => { if (yearsAsc.length === 0) return; const base = yearIndex >= 0 ? yearIndex : yearsAsc.length - 1; const next = Math.max(0, Math.min(yearsAsc.length - 1, base + dir)); setView(String(yearsAsc[next].year)); };
    const panel = active === 'overview' ? <Overview stats={current} previous={previous} selectedYear={selectedYear} /> : active === 'breakdowns' ? <Breakdowns stats={current} previous={previous} /> : active === 'progression' ? <Progression stats={current} previous={previous} /> : <Archive stats={current} previous={previous} selectedYear={selectedYear} />;
    return <AppLayout title="Stats"><section className="px-4 pb-8 md:pl-[88px] md:pr-6"><div className="mx-auto max-w-[1540px]"><header className="mb-5 rounded-[34px] bg-black p-5 text-white shadow-[0_24px_80px_rgb(0_0_0/0.20)] md:p-7"><div className="grid gap-6 xl:grid-cols-[1fr_auto] xl:items-end"><div><div className="text-xs font-black uppercase tracking-[0.28em] text-[#b7ff63]/70">{selectedYear ? `${selectedYear.year} confirmed snapshot` : 'All-time live profile'}</div><h1 className="mt-2 text-5xl font-black tracking-[-0.06em] md:text-7xl">Stats</h1><p className="mt-3 max-w-3xl text-sm font-bold leading-relaxed text-white/45 md:text-base">Snapshot years use confirmed archive data. All-time uses the live library. Move through modules like a slideshow without unrelated sections.</p></div><div className="grid gap-3 sm:grid-cols-[auto_auto] sm:items-center"><button type="button" onClick={() => setView('all-time')} className={`rounded-[22px] px-6 py-4 text-sm font-black uppercase tracking-[0.16em] transition ${view === 'all-time' ? 'bg-[#b7ff63] text-black' : 'bg-white/8 text-white/50 hover:text-white'}`}>All Time</button><div className="flex items-center justify-between gap-2 rounded-[24px] bg-white/8 p-2"><button type="button" onClick={() => stepYear(-1)} disabled={yearsAsc.length === 0 || yearIndex <= 0} className="grid size-12 place-items-center rounded-[18px] bg-black text-white ring-1 ring-white/10 transition hover:text-[#b7ff63] disabled:cursor-not-allowed disabled:opacity-25"><ChevronLeft size={18} /></button><button type="button" onClick={() => displayedYear && setView(String(displayedYear))} disabled={!displayedYear} className={`min-w-[126px] rounded-[18px] px-6 py-3 text-center text-xl font-black tracking-[0.1em] transition disabled:cursor-not-allowed disabled:opacity-35 ${selectedYear ? 'bg-[#b7ff63] text-black' : 'bg-white/7 text-white/55 hover:text-white'}`}>{displayedYear ?? '—'}</button><button type="button" onClick={() => stepYear(1)} disabled={yearsAsc.length === 0 || yearIndex >= yearsAsc.length - 1} className="grid size-12 place-items-center rounded-[18px] bg-black text-white ring-1 ring-white/10 transition hover:text-[#b7ff63] disabled:cursor-not-allowed disabled:opacity-25"><ChevronRight size={18} /></button></div></div></div></header><main className="min-h-[620px] rounded-[34px] border border-black/8 bg-white/35 p-4 shadow-[inset_0_1px_0_rgb(255_255_255/0.58)] md:p-5">{panel}</main><SlideNav active={active} setActive={setActive} /></div></section></AppLayout>;
}
